-   id: nglint
    name: nglint
    description: Runs ng lint
    entry: nglint.py
    language: script

    # Use additional_dependencies to install the actual node package
    minimum_pre_commit_version: 0.12.0
